export interface RepoConfig {
	name: string;
	special?: boolean;
}

export const REPOS: RepoConfig[] = [
	{ name: 'iiitl/student-hub', special: true },
	{ name: 'iiitl/pygame-arcade' },
	{ name: 'iiitl/whisper' },
	{ name: 'iiitl/warp' },
	{ name: 'iiitl/Victory-Verse' },
	{ name: 'iiitl/HeartSync' },
	{ name: 'iiitl/yt-music-tauri' },
	{ name: 'iiitl/OxiDock' },
	{ name: 'iiitl/PerOXO' },
	{ name: 'iiitl/Drishya' },
	{ name: 'iiitl/Shadowlock' },
	{ name: 'iiitl/PlanWise' },
	{ name: 'iiitl/Tap2Eat' },
	{ name: 'iiitl/decentralized-uptime-monitoring' },
	{ name: 'iiitl/Student-Hub-App' },
	{ name: 'iiitl/StonkSchool' },
	{ name: 'iiitl/git-repo-2026' },
	{ name: 'iiitl/CargoCut' },
	{ name: 'iiitl/Bash-Repo-2026' },
	{ name: 'iiitl/BountyRaffle' },
	{ name: 'iiitl/Cp_Discord_Bot' },
	{ name: 'iiitl/cp-rs' },
	{ name: 'iiitl/Linear-Regression' },
	{ name: 'iiitl/K-Means-Clustering' },
	{ name: 'iiitl/Logistic-Regression' },
	{ name: 'iiitl/Neural-Networks' },
	{ name: 'iiitl/Decision-Tree' },
	{ name: 'iiitl/anilist_moe' },
	{ name: 'iiitl/breach-battle' },
	{ name: 'iiitl/AlgoJudge' },
	{ name: 'iiitl/EDA-IPL' },
	{ name: 'iiitl/smartdoc-workshop' },
	{ name: 'iiitl/ChatterBox' },
	{ name: 'iiitl/Local-Link' },
	{ name: 'iiitl/CForge' },
	{ name: 'iiitl/StocksApp' },
	{ name: 'iiitl/Wanderlens' },
	{ name: 'iiitl/CodeForces' },
	{ name: 'iiitl/chuck' },
	{ name: 'iiitl/ScreenExtractor' },
	{ name: 'iiitl/NewTab-Overdrive' },
	{ name: 'iiitl/Opensource_Compass' },
	{ name: 'iiitl/insane-vitepress' },
	{ name: 'iiitl/Zonic' },
	{ name: 'iiitl/mintlify-docs' },
	{ name: 'iiitl/Private' },
	{ name: 'iiitl/MessEase', special: true },
	{ name: 'iiitl/alumni', special: true },
	{ name: 'iiitl/MissionSakhi' },
	{ name: 'iiitl/Crate' },
	{ name: 'iiitl/Chat-app' },
];
